# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow3.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(644, 470)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tiltSlider = QtWidgets.QSlider(self.centralwidget)
        self.tiltSlider.setMinimum(-5)
        self.tiltSlider.setMaximum(5)
        self.tiltSlider.setOrientation(QtCore.Qt.Vertical)
        self.tiltSlider.setObjectName("tiltSlider")
        self.horizontalLayout_2.addWidget(self.tiltSlider)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.labelFrame = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.labelFrame.sizePolicy().hasHeightForWidth())
        self.labelFrame.setSizePolicy(sizePolicy)
        self.labelFrame.setText("")
        self.labelFrame.setObjectName("labelFrame")
        self.horizontalLayout.addWidget(self.labelFrame)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton1.setObjectName("pushButton1")
        self.verticalLayout.addWidget(self.pushButton1)
        self.pushButton2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton2.setObjectName("pushButton2")
        self.verticalLayout.addWidget(self.pushButton2)
        self.pushButton3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton3.setObjectName("pushButton3")
        self.verticalLayout.addWidget(self.pushButton3)
        self.pushButton4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton4.setObjectName("pushButton4")
        self.verticalLayout.addWidget(self.pushButton4)
        self.pushButtonReithalle = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonReithalle.setObjectName("pushButtonReithalle")
        self.verticalLayout.addWidget(self.pushButtonReithalle)
        self.pushButtonParken1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonParken1.setObjectName("pushButtonParken1")
        self.verticalLayout.addWidget(self.pushButtonParken1)
        self.pushButtonParken2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonParken2.setObjectName("pushButtonParken2")
        self.verticalLayout.addWidget(self.pushButtonParken2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.pushButtonTest = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonTest.setObjectName("pushButtonTest")
        self.verticalLayout.addWidget(self.pushButtonTest)
        self.pushButtonRecord = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonRecord.setObjectName("pushButtonRecord")
        self.verticalLayout.addWidget(self.pushButtonRecord)
        self.pushButtonSnapshot = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonSnapshot.setObjectName("pushButtonSnapshot")
        self.verticalLayout.addWidget(self.pushButtonSnapshot)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 644, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSave_as = QtWidgets.QAction(MainWindow)
        self.actionSave_as.setObjectName("actionSave_as")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionHelp = QtWidgets.QAction(MainWindow)
        self.actionHelp.setObjectName("actionHelp")
        self.menuFile.addAction(self.actionSave_as)
        self.menuFile.addAction(self.actionQuit)
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addAction(self.actionHelp)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.actionQuit.triggered.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton1.setText(_translate("MainWindow", "Stall"))
        self.pushButton2.setText(_translate("MainWindow", "Stübchen"))
        self.pushButton3.setText(_translate("MainWindow", "Waschplatz"))
        self.pushButton4.setText(_translate("MainWindow", "Tor"))
        self.pushButtonReithalle.setText(_translate("MainWindow", "Reithalle"))
        self.pushButtonParken1.setText(_translate("MainWindow", "Parken 1"))
        self.pushButtonParken2.setText(_translate("MainWindow", "Parken 2"))
        self.pushButtonTest.setText(_translate("MainWindow", "Event"))
        self.pushButtonRecord.setText(_translate("MainWindow", "Record"))
        self.pushButtonSnapshot.setText(_translate("MainWindow", "Picture"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionSave_as.setText(_translate("MainWindow", "Save as ..."))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionHelp.setText(_translate("MainWindow", "Help"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

